# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xs2auth', '0002_auto_20160223_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('authtoken.token',),
        ),
        migrations.AddField(
            model_name='userwithemail',
            name='provider_id',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=b'provider_id'),
        ),
        migrations.AddField(
            model_name='userwithemail',
            name='username',
            field=models.TextField(db_index=True,  max_length=255, unique=True, default="test", verbose_name=b'username'),
            preserve_default=False,
        ),
    ]
