# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xs2auth', '0003_auto_20160421_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithemail',
            name='provider',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name=b'provider'),
        ),
    ]
